config/routes.rb
Rails.application.routes.draw do
  resources :pins  do
    member do 
    put "like" => "pins#upvote"
      end
  end
  devise_for :users
 get 'about' => 'pages#about'

root 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    
    validates :description, presence: true
    validates :image, presence: true
acts_as_votable
has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }
validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
validates_attachment :image, presence: true,
size: { in: 0..5.megabytes }


belongs_to :user    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

acts_as_voter
 has_many :pins 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show] 
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def upvote
  @pin.upvote_by current_user
    redirect_to pins_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="index_footer">
	<footer>
	<p>
	<%= link_to "Rails Web App", "http://hasanme.com" %>
	  by <small>
	    <%=  link_to "Hasan Ahmed", "http://hasanme.com" %>
	  </small>
	</p>
	</footer/>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails Web App", root_path, class: "navbar-brand" %>
      
    </div> <!-- end div class="navbar-header" -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav pull-right">
           <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      
      <ul class="nav pull-right">
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      </ul>
      <ul class="nav pull-right">
         <li> <%= link_to "Add +", new_pin_path %> </li>

      </ul>
      <ul class="nav pull-right">
        <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div> <!-- end div class="collapse navbar-collapse" -->
  </div> <!-- end div class="container" -->
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang='en'>

    <head>
        <meta charset="utf-8">
        <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>

        <title>Hasan's Web App</title>

        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>

    </head>
    <body>

        <%= render 'layouts/header' %>

        <div class="container">

        <% flash.each do |name, msg| %>

                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>

        <% end %>

            <%= yield %>

            <%= render 'layouts/footer' %>

        </div>
    </body>
</html>

app/views/pages/_home.html.erb
<!-- you can put anything you like here -->
<% unless user_signed_in? %>

    <div class="jumbotron">
    
        <h1>Welcome to  My Rails Web App!</h1>
    
        <h2>Hi, This is Hasan.</h2>
            <p>
                I am glad that you have found the homepage of
                <%=  link_to "Hasan's Web Rails ",  "http://hasanme.com"%>
                application.
            </p>
            <p>
                <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-lg"   %>
            </p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<h3>
<%= link_to "Hasan's Web App", "http://hasanme.com" %> is a project
on <%= link_to "Ruby On Rails", "http://ruby-lang.org" %> to make a sample web app
which let users post there pictures .

</h3>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class:"alert alert-error" %>
  <%= f.full_error :image_content_type, class:"alert alert-error" %>

<%= f.input :image, label: "Upload an image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="pins" class="transitions-enabled">
    <div class="box panel panel-default">

	 <%= link_to (image_tag pin.image(:medium)), pin %>
		<div class="panel-body">
	 	<p class="pin.description">
		<%= pin.description %>
	</p>
	<p>	
		<strong>
			Uploaded by <%= pin.user.name %>
		</strong>
	</p>	
	<p>	
		<%= link_to like_pin_path(pin), class: "like", method: :put do %>
		<button type ="button" class ="btn btn-success" aria-label="Left Align">
		<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
		<span class="badge"><%= pin.get_upvotes.size %></span>
		</button>
		<% end %>
		  <% if current_user == pin.user %> 
	
		
		<%= link_to edit_pin_path(pin) do %>
		
		<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit

		<% end %>

		<%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
		
		<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete

		<% end %>
	</p>

		<% end %> 

	</div>
	</div>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>
<%= image_tag @pin.image.url(:medium)%>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
<div id="pins">

	<%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
 <%= link_to 'Back', pins_path %>

<div class="showimg">
    <%= image_tag @pin.image.url(:medium)%>
</div>
    <p class="description">
      <%= @pin.description %>
    </p>
    
    <p>
      <strong>
        Uploaded by <%= @pin.user.name %>
      </strong>
      
    </p>
    <% if current_user == @pin.user %>
      <%= link_to edit_pin_path(@pin) do %> 
<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit
      <% end %>
              <% end %>  